name: ago-docs

services:
    app:
        image: ago-docs
        container_name: ago-docs
        build:
            context: .
            dockerfile: Containerfile
        volumes:
            - .:/app:z
        ports:
            - 3000:5173
